package:
  name: phyloligo
  version: v1.0

source:
  git_rev: 9756d8f
  git_url: https://github.com/itsmeludo/PhylOligo.git

build:
  number: 1
  string: 9756d8f

requirements:
  host:
    - python>=3.7
    - setuptools
    - git

  run:
    - python>=3.7
    - biopython>=1.68
    - scikit-learn=0.19.1
    - numpy>=1.11.2
    - cython>=0.25.1
    - hdbscan
    - seaborn
    - matplotlib
    - scoop
    - h5py
    - emboss
    - samtools
    - r-base
    - r-ape 
    - r-getopt
    - r-gplots

about:
  home: https://github.com/itsmeludo/PhylOligo
  license: GPLv3
  license_file: LICENSE
