package:
  name: phyloligo
  version: v0.9_3693ac8

source:
  git_rev: 3693ac8
  git_url: https://github.com/itsmeludo/PhylOligo.git

build:
  number: 1
  string: 3693ac8

requirements:
  host:
    - python>=3.7
    - setuptools
    - git

  run:
    - python>=3.7
    - biopython>=1.68
    - scikit-learn=0.19.1
    - numpy>=1.11.2
    - cython>=0.25.1
    - hdbscan
    - seaborn
    - matplotlib
    - scoop
    - h5py

about:
  home: https://github.com/itsmeludo/PhylOligo
  license: GPLv3
  license_file: LICENSE
